name: flexiscan101
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.4.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  dio: ^5.7.0
  smooth_page_indicator: ^1.2.0+3
  tuple: ^2.0.0
  sqflite: ^2.3.3+1
  intl: ^0.19.0
  conditional_builder_null_safety: ^0.0.6
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2
  fluttertoast: ^8.2.8
  carousel_slider: ^5.0.0
  rive: ^0.13.16
  agora_rtc_engine: 5.2.0 
  permission_handler:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  path: ^1.8.0

flutter:
  uses-material-design: true

  assets:
    - asset/images/Idle.gif
    - asset/images/Fly1.gif
    - asset/images/Fly2.gif
    - asset/images/Selected.gif
    - asset/images/Selected 2.gif
    - asset/images/Selected3.gif
    - asset/images/Error_Start.gif
    - asset/images/Error_Start2.gif
    - asset/images/Error_Start 3.gif
    - asset/images/Removal-683.png
    - asset/images/Doctor.png
    - asset/images/Patient.png
    - asset/images/Pointing.gif
    - asset/images/LookingUp.gif
    - asset/images/LookingDown.gif
    - asset/images/HandsUp.gif
    - assets/test.riv


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
