name: flexiscan101
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bluetooth_serial: any
  font_awesome_flutter: ^10.4.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  dio: ^5.7.0
  tuple: ^2.0.0
  sqflite: ^2.3.3+1
  intl: ^0.19.0
  conditional_builder_null_safety: ^0.0.6
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  path: ^1.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/Idle.gif
    - assets/Fly1.gif
    - assets/Fly2.gif
    - assets/Selected.gif
    - assets/Selected 2.gif
    - assets/Selected3.gif
    - assets/Error_Start.gif
    - assets/Error_Start2.gif
    - assets/Error_Start 3.gif
